export { default as Header } from "./Header/Header";
export { default as AllContacts } from "./Contacts/AllContacts/AllContacts";
export { default as Favorites } from "./Contacts/Favorites/Favorites";
export { default as DeleteDialog } from "./DeleteDialog/DeleteDialog";
export { default as Navbar } from "./Navbar/Navbar";
export { default as SearchBar } from "./SearchBar/SearchBar";
export { default as AddNew } from "./Contacts/AddNew/AddNew";
export { default as EditContact } from "./Contacts/EditContact/EditContact";
export { default as ContactDetail } from "./Contacts/ContactDetails/ContactDetails";
